export const ENDPOINTS = {
  health: '/health',
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    me: '/auth/me',
    contexts: '/auth/contexts',
    switchContext: '/auth/switch-context',
  },
  licenses: '/licenses',
  content: {
    sample: '/content/sample',
  },
  settings: {
    privacy: '/settings/privacy',
  },
  schools: {
    map: '/schools/map',
    nearby: '/schools/nearby',
    detail: (id) => `/schools/${id}`,
    courses: (id) => `/schools/${id}/courses`,
    coaches: (id) => `/schools/${id}/coaches`,
  },
  reviews: {
    bySchool: (schoolId) => `/reviews/school/${schoolId}`,
    create: '/reviews',
  },
  profile: '/profile',
  location: '/location',
  enrollments: {
    list: '/enrollments',
    create: '/enrollments',
    retake: '/enrollments/retake',
    detail: (id) => `/enrollments/${id}`,
    cancel: (id) => `/enrollments/${id}/cancel`,
    paymentInitiate: (id) => `/enrollments/${id}/payment/initiate`,
    paymentConfirm: (id) => `/enrollments/${id}/payment/confirm`,
    retakePaymentInitiate: (id) => `/enrollments/${id}/payment/retake/initiate`,
    retakePaymentConfirm: (id) => `/enrollments/${id}/payment/retake/confirm`,
  },
  notifications: '/notifications',
  search: '/search',
  documents: '/documents',
  preRegistrations: '/pre-registrations',
  schoolApplications: '/school-applications',
  student: {
    dashboard: '/student/dashboard',
    archive: '/student/archive',
    statistics: '/student/statistics',
    theory: '/student/content/theory',
    theoryDetail: (id) => `/student/content/theory/${id}`,
    shared: '/student/content/shared',
    specific: '/student/content/specific',
    videos: '/student/content/videos',
    unlock: '/student/content/unlock',
    practiceStart: '/student/practice/start',
    practiceSubmit: '/student/practice/submit',
    practice: '/student/practice',
    examInfo: '/student/exam-info',
    certificates: '/student/certificates',
    lessons: '/student/lessons',
    autoBookLesson: '/student/lessons/auto-book',
    eligibleCoaches: '/student/lessons/eligible-coaches',
  },
  coach: {
    schedule: '/coach/schedule',
    students: '/coach/students',
    completeLesson: (id) => `/coach/lessons/${id}/complete`,
    notes: '/coach/notes',
    editQuestion: '/coach/edits/questions',
    editContent: '/coach/edits/content',
  },
  manager: {
    courses: '/manager/courses',
    closeCourse: (id) => `/manager/courses/${id}/close`,
    launchCourse: (id) => `/manager/courses/${id}/launch`,
    enrollmentQueue: (courseId) => `/manager/courses/${courseId}/enrollments`,
    rosterCandidates: (courseId) => `/manager/courses/${courseId}/roster-candidates`,
    acceptEnrollment: (id) => `/manager/enrollments/${id}/accept`,
    rejectEnrollment: (id) => `/manager/enrollments/${id}/reject`,
    instructors: '/manager/instructors',
    assignInstructor: '/manager/instructors',
    updateInstructor: (id) => `/manager/instructors/${id}`,
    questionBanks: '/manager/question-banks',
    addQuestion: (bankId) => `/manager/question-banks/${bankId}/questions`,
    pendingEdits: '/manager/content-edits/pending',
    reviewEdit: (id) => `/manager/content-edits/${id}/review`,
    rosters: '/manager/rosters',
    submitRoster: (id) => `/manager/rosters/${id}/submit`,
    examResults: '/manager/exam-results',
    schedule: '/manager/schedule',
  },
  admin: {
    pricing: '/admin/pricing',
    commission: '/admin/commission',
    licenses: '/admin/licenses',
    schools: '/admin/schools',
    schoolDetail: (id) => `/admin/schools/${id}`,
    deleteSchool: (id) => `/admin/schools/${id}`,
    applications: '/admin/school-applications',
    reviewApplication: (id) => `/admin/school-applications/${id}/review`,
    users: '/admin/users',
    assignRole: '/admin/users/roles',
    suspendUser: (id) => `/admin/users/${id}/status`,
    ads: '/admin/ads',
    distributeRosters: '/admin/traffic/distribute',
    audit: '/admin/audit',
    reports: '/admin/reports',
    reviewsPending: '/admin/reviews/pending',
    moderateReview: (id) => `/admin/reviews/${id}/moderate`,
    privacy: '/admin/settings/privacy',
    registration: '/admin/settings/registration',
    createTrafficAccount: '/admin/users/traffic-accounts',
  },
  traffic: {
    dashboard: '/traffic/dashboard',
    rosters: '/traffic/rosters',
    rosterDetail: (id) => `/traffic/rosters/${id}`,
    schedules: '/traffic/schedules',
    scheduleDetail: (id) => `/traffic/schedules/${id}`,
    results: '/traffic/results',
    resultsBulk: '/traffic/results/bulk',
    enrollments: '/traffic/enrollments',
    licenses: '/traffic/licenses',
  },
  rosters: {
    verify: (token) => `/rosters/verify/${token}`,
  },
}
