export const ENDPOINTS = {
  health: '/health',
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    refresh: '/auth/refresh',
    forgotPassword: '/auth/forgot-password',
    verifyResetCode: '/auth/verify-reset-code',
    resetPassword: '/auth/reset-password',
    me: '/auth/me',
    contexts: '/auth/contexts',
    switchContext: '/auth/switch-context',
  },
  licenses: '/licenses',
  content: {
    sample: '/content/sample',
  },
  ads: {
    list: '/ads',
  },
  media: {
    upload: '/media',
    file: (id) => `/media/${id}`,
  },
  faq: '/faq',
  requirements: '/requirements',
  testimonials: '/testimonials',
  settings: {
    privacy: '/settings/privacy',
  },
  schools: {
    map: '/schools/map',
    nearby: '/schools/nearby',
    detail: (id) => `/schools/${id}`,
    courses: (id) => `/schools/${id}/courses`,
    coaches: (id) => `/schools/${id}/coaches`,
  },
  reviews: {
    bySchool: (schoolId) => `/reviews/school/${schoolId}`,
    create: '/reviews',
  },
  profile: '/profile',
  location: '/location',
  enrollments: {
    list: '/enrollments',
    create: '/enrollments',
    retake: '/enrollments/retake',
    detail: (id) => `/enrollments/${id}`,
    cancel: (id) => `/enrollments/${id}`,
    paymentInitiate: (id) => `/enrollments/${id}/payment/initiate`,
    paymentClaim: (id) => `/enrollments/${id}/payment/claim`,
    payFromWallet: (id) => `/enrollments/${id}/pay-from-wallet`,
    retakePaymentInitiate: (id) => `/enrollments/${id}/payment/retake/initiate`,
    retakePaymentClaim: (id) => `/enrollments/${id}/payment/retake/claim`,
    retakePayFromWallet: (id) => `/enrollments/${id}/payment/retake/pay-from-wallet`,
  },
  notifications: '/notifications',
  search: '/search',
  documents: '/documents',
  preRegistrations: '/pre-registrations',
  schoolApplications: '/school-applications',
  student: {
    dashboard: '/student/dashboard',
    archive: '/student/archive',
    statistics: '/student/statistics',
    theory: '/student/content/theory',
    theoryDetail: (id) => `/student/content/theory/${id}`,
    theoryComplete: (id) => `/student/content/theory/${id}/complete`,
    shared: '/student/content/shared',
    specific: '/student/content/specific',
    videos: '/student/content/videos',
    unlock: '/student/content/unlock',
    practiceStart: '/student/practice/start',
    practiceSubmit: '/student/practice/submit',
    practice: '/student/practice',
    examInfo: '/student/exam-info',
    certificates: '/student/certificates',
    lessons: '/student/lessons',
    autoBookLesson: '/student/lessons/auto-book',
    eligibleCoaches: '/student/lessons/eligible-coaches',
    availableCoaches: '/student/lessons/available-coaches',
    cancelLesson: (id) => `/student/lessons/${id}/cancel`,
  },
  coach: {
    schedule: '/coach/schedule',
    students: '/coach/students',
    completeLesson: (id) => `/coach/lessons/${id}/complete`,
    cancelLesson: (id) => `/coach/lessons/${id}/cancel`,
    postponeLesson: (id) => `/coach/lessons/${id}/postpone`,
    confirmLesson: (id) => `/coach/lessons/${id}/confirm`,
    notes: '/coach/notes',
    questionBanks: '/coach/question-banks',
    content: '/coach/content',
    editQuestion: '/coach/edits/questions',
    editContent: '/coach/edits/content',
  },
  manager: {
    courses: '/manager/courses',
    course: (id) => `/manager/courses/${id}`,
    closeCourse: (id) => `/manager/courses/${id}/close`,
    launchCourse: (id) => `/manager/courses/${id}/launch`,
    enrollmentQueue: (courseId) => `/manager/courses/${courseId}/enrollments`,
    awaitingPaymentQueue: (courseId) => `/manager/courses/${courseId}/enrollments/awaiting-payment`,
    rosterCandidates: (courseId) => `/manager/courses/${courseId}/roster-candidates`,
    acceptEnrollment: (id) => `/manager/enrollments/${id}/accept`,
    rejectEnrollment: (id) => `/manager/enrollments/${id}/reject`,
    confirmEnrollmentPayment: (id) => `/manager/enrollments/${id}/payment/confirm`,
    instructors: '/manager/instructors',
    instructor: (id) => `/manager/instructors/${id}`,
    assignInstructor: '/manager/instructors',
    updateInstructor: (id) => `/manager/instructors/${id}`,
    questionBanks: '/manager/question-banks',
    questionBank: (bankId) => `/manager/question-banks/${bankId}`,
    addQuestion: (bankId) => `/manager/question-banks/${bankId}/questions`,
    question: (bankId, questionId) => `/manager/question-banks/${bankId}/questions/${questionId}`,
    updateQuestion: (bankId, questionId) => `/manager/question-banks/${bankId}/questions/${questionId}`,
    theoryContent: '/manager/content/theory',
    theoryContentItem: (id) => `/manager/content/theory/${id}`,
    pendingEdits: '/manager/content-edits/pending',
    reviewEdit: (id) => `/manager/content-edits/${id}/review`,
    rosters: '/manager/rosters',
    submitRoster: (id) => `/manager/rosters/${id}/submit`,
    schedule: '/manager/schedule',
  },
  admin: {
    pricing: '/admin/pricing',
    commission: '/admin/commission',
    licenses: '/admin/licenses',
    schools: '/admin/schools',
    schoolDetail: (id) => `/admin/schools/${id}`,
    assignSchoolManager: (id) => `/admin/schools/${id}/manager`,
    deleteSchool: (id) => `/admin/schools/${id}`,
    applications: '/admin/school-applications',
    reviewApplication: (id) => `/admin/school-applications/${id}/review`,
    users: '/admin/users',
    userDetail: (id) => `/admin/users/${id}`,
    assignRole: '/admin/users/roles',
    suspendUser: (id) => `/admin/users/${id}/status`,
    ads: '/admin/ads',
    distributeRosters: '/admin/traffic/distribute',
    audit: '/admin/audit',
    reports: '/admin/reports',
    reviewsPending: '/admin/reviews/pending',
    moderateReview: (id) => `/admin/reviews/${id}/moderate`,
    privacy: '/admin/settings/privacy',
    registration: '/admin/settings/registration',
    createTrafficAccount: '/admin/users/traffic-accounts',
    confirmEnrollmentPayment: (id) => `/admin/enrollments/${id}/payment/confirm`,
    userWallet: (id) => `/admin/users/${id}/wallet`,
    creditUserWallet: (id) => `/admin/users/${id}/wallet/credit`,
    faq: '/admin/faq',
    faqDetail: (id) => `/admin/faq/${id}`,
    requirements: '/admin/requirements',
    requirementDetail: (id) => `/admin/requirements/${id}`,
    testimonials: '/admin/testimonials',
    testimonialDetail: (id) => `/admin/testimonials/${id}`,
    compliance: '/admin/compliance',
    complianceDetail: (id) => `/admin/compliance/${id}`,
    approveCompliance: (id) => `/admin/compliance/${id}/approve`,
    rejectCompliance: (id) => `/admin/compliance/${id}/reject`,
  },
  traffic: {
    dashboard: '/traffic/dashboard',
    rosters: '/traffic/rosters',
    rosterDetail: (id) => `/traffic/rosters/${id}`,
    schedules: '/traffic/schedules',
    scheduleDetail: (id) => `/traffic/schedules/${id}`,
    results: '/traffic/results',
    resultsBulk: '/traffic/results/bulk',
    enrollments: '/traffic/enrollments',
    licenses: '/traffic/licenses',
  },
  rosters: {
    verify: (token) => `/rosters/verify/${token}`,
  },
  verify: {
    statistics: (token) => `/verify/statistics/${token}`,
    certificate: (token) => `/verify/certificate/${token}`,
    roster: (token) => `/verify/roster/${token}`,
  },
}
