export const ROUTES = {
  HOME: '/',
  LICENSES: '/licenses',
  LICENSE_DETAIL: '/licenses/:code',
  SCHOOLS_NEARBY: '/schools/nearby',
  SCHOOL_DETAIL: '/schools/:id',
  REQUIREMENTS: '/requirements',
  SAMPLE: '/sample',
  FAQ: '/faq',
  ADD_SCHOOL: '/add-school',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  ENROLL: '/enroll',
  NOTIFICATIONS: '/notifications',
  STUDENT: '/student',
  COACH: '/coach',
  MANAGER: '/manager',
  ADMIN: '/admin',
  TRAFFIC: '/traffic',
  UNAUTHORIZED: '/unauthorized',
  LOGOUT: '/logout',
}
