export const SEARCH_TYPE_LABELS = {
  page: 'صفحة',
  school: 'مدرسة',
  license: 'رخصة',
  notification: 'إشعار',
  theory: 'محتوى نظري',
  video: 'فيديو',
  lesson: 'موعد',
  student: 'طالب',
  note: 'ملاحظة',
  course: 'دورة',
  enrollment: 'اشتراك',
  instructor: 'مدرب',
  roster: 'قائمة',
  user: 'مستخدم',
  application: 'طلب مدرسة',
  audit: 'تدقيق',
  schedule: 'موعد امتحان',
  result: 'نتيجة',
}
