/**
 * خريطة الشاشات 34 — من drivehub_screens_design
 * للربط بين التصميم والـ routes/features
 */
export const SCREEN_MAP = {
  1: { title: 'الصفحة الرئيسية', feature: 'home', route: '/' },
  2: { title: 'استكشاف المنصة', feature: 'home/explore', route: '/licenses' },
  6: { title: 'تفاصيل المدرسة', feature: 'schools', route: '/schools/:id' },
  3: { title: 'تسجيل الرخصة', feature: 'enrollment', route: '/enroll' },
  4: { title: 'لوحة تحكم الطالب', feature: 'student', route: '/student' },
  5: { title: 'تعلم القيادة', feature: 'student/learning', route: '/student/theory' },
  7: { title: 'قائمة الطلاب', feature: 'coach', route: '/coach/students' },
  8: { title: 'تقييم الدرس العملي', feature: 'coach', route: '/coach/lessons' },
  9: { title: 'جدول المدرب', feature: 'coach', route: '/coach/schedule' },
  10: { title: 'لوحة تحكم المدرب', feature: 'coach', route: '/coach' },
  11: { title: 'لوحة مدير المدرسة', feature: 'manager', route: '/manager' },
  12: { title: 'إدارة الدورات', feature: 'manager/courses', route: '/manager/courses' },
  13: { title: 'طلبات الالتحاق', feature: 'manager/enrollments', route: '/manager/enrollments' },
  14: { title: 'إدارة المدربين', feature: 'manager/instructors', route: '/manager/instructors' },
  15: { title: 'بوابة المرور', feature: 'traffic', route: '/traffic' },
  16: { title: 'بوابة المرور', feature: 'traffic', route: '/traffic/schedules' },
  17: { title: 'تصدير التقارير', feature: 'admin/reports', route: '/admin/reports' },
  18: { title: 'إدارة المدارس', feature: 'admin/schools', route: '/admin/schools' },
  19: { title: 'لوحة Admin', feature: 'admin', route: '/admin' },
  20: { title: 'الأسعار والإيرادات', feature: 'admin/pricing', route: '/admin/pricing' },
  21: { title: 'التحقق والامتثال', feature: 'admin/compliance', route: '/admin/compliance' },
  22: { title: 'المستخدمين والصلاحيات', feature: 'admin/users', route: '/admin/users' },
  23: { title: 'إعدادات النظام', feature: 'admin/settings', route: '/admin/settings' },
  24: { title: 'سجل التدقيق', feature: 'admin/audit', route: '/admin/audit' },
  25: { title: 'تسجيل الدخول', feature: 'auth', route: '/login' },
  26: { title: 'تسجيل طالب', feature: 'auth', route: '/register' },
  27: { title: 'تسجيل الخروج', feature: 'auth', route: '/logout' },
  28: { title: 'تسجيل مدرسة', feature: 'add-school', route: '/add-school' },
  29: { title: 'لوحة Admin Ultra', feature: 'admin', route: '/admin' },
  30: { title: 'إدارة المدارس Ultra', feature: 'admin/schools', route: '/admin/schools' },
  31: { title: 'تسجيل الدخول Ultra', feature: 'auth', route: '/login' },
  32: { title: 'الأسعار Ultra', feature: 'admin/pricing', route: '/admin/pricing' },
  33: { title: 'المستخدمين Ultra', feature: 'admin/users', route: '/admin/users' },
  34: { title: 'التحقق Ultra', feature: 'admin/compliance', route: '/admin/compliance' },
}
