module.exports = {
    authService: require('./auth.service'),
    userService: require('./user.service'),
    schoolService: require('./school.service'),
    licenseService: require('./license.service'),
    enrollmentService: require('./enrollment.service'),
    courseService: require('./course.service'),
    paymentService: require('./payment.service'),
    notificationService: require('./notification.service'),
    documentService: require('./document.service'),
    auditService: require('./audit.service'),
    locationService: require('./location.service'),
    contentService: require('./content.service'),
    examService: require('./exam.service'),
    trafficService: require('./traffic.service'),
    instructorService: require('./instructor.service'),
    lessonService: require('./lesson.service'),
    rosterService: require('./roster.service'),
    reviewService: require('./review.service'),
    platformService: require('./platform.service'),
    schoolApplicationService: require('./schoolApplication.service'),
    preRegistrationService: require('./preRegistration.service'),
    studentService: require('./student.service'),
};
