module.exports = {
    healthController: require('./health.controller'),
    authController: require('./auth.controller'),
    profileController: require('./profile.controller'),
    locationController: require('./location.controller'),
    licensesController: require('./licenses.controller'),
    schoolsController: require('./schools.controller'),
    enrollmentsController: require('./enrollments.controller'),
    notificationsController: require('./notifications.controller'),
    documentsController: require('./documents.controller'),
    reviewsController: require('./reviews.controller'),
    preRegistrationsController: require('./preRegistrations.controller'),
    schoolApplicationsController: require('./schoolApplications.controller'),
    studentController: require('./student.controller'),
    coachController: require('./coach.controller'),
    managerController: require('./manager.controller'),
    adminController: require('./admin.controller'),
    trafficController: require('./traffic.controller'),
};
