module.exports = {
    messages: require('./messages'),
    chains: require('./chains'),
    ...require('./common.validator'),
    ...require('./auth.validator'),
    ...require('./user.validator'),
    ...require('./location.validator'),
    ...require('./school.validator'),
    ...require('./license.validator'),
    ...require('./enrollment.validator'),
    ...require('./course.validator'),
    ...require('./payment.validator'),
    ...require('./document.validator'),
    ...require('./notification.validator'),
    ...require('./content.validator'),
    ...require('./instructor.validator'),
    ...require('./lesson.validator'),
    ...require('./exam.validator'),
    ...require('./roster.validator'),
    ...require('./review.validator'),
    ...require('./admin.validator'),
};
