import { apiClient, ENDPOINTS } from '@/lib/api'
import { buildQueryString } from '@/lib/helpers/pagination'

export const adminService = {
  listPricing: () => apiClient.get(ENDPOINTS.admin.pricing),
  upsertPricing: (data) => apiClient.put(ENDPOINTS.admin.pricing, data),
  updateCommission: (commission) => apiClient.patch(ENDPOINTS.admin.commission, { commission }),
  listLicenses: () => apiClient.get(ENDPOINTS.admin.licenses),
  upsertLicense: (data) => apiClient.put(`${ENDPOINTS.admin.licenses}/categories`, data),
  upsertLicenseSubType: (data) => apiClient.put(`${ENDPOINTS.admin.licenses}/sub-types`, data),
  listSchools: (params) => apiClient.get(`${ENDPOINTS.admin.schools}${buildQueryString(params)}`),
  getSchool: (id) => apiClient.get(ENDPOINTS.admin.schoolDetail(id)),
  createSchool: (data) => apiClient.post(ENDPOINTS.admin.schools, data),
  updateSchool: (id, data) => apiClient.patch(ENDPOINTS.admin.schoolDetail(id), data),
  deleteSchool: (id) => apiClient.delete(ENDPOINTS.admin.deleteSchool(id)),
  listApplications: () => apiClient.get(ENDPOINTS.admin.applications),
  reviewApplication: (id, data) => apiClient.post(ENDPOINTS.admin.reviewApplication(id), data),
  listComplianceRequests: (params) =>
    apiClient.get(`${ENDPOINTS.admin.compliance}${buildQueryString(params)}`),
  getComplianceRequest: (id) => apiClient.get(ENDPOINTS.admin.complianceDetail(id)),
  approveComplianceRequest: (id) => apiClient.post(ENDPOINTS.admin.approveCompliance(id)),
  rejectComplianceRequest: (id, rejectionReason) =>
    apiClient.post(ENDPOINTS.admin.rejectCompliance(id), { rejectionReason }),
  listUsers: (params) => apiClient.get(`${ENDPOINTS.admin.users}${buildQueryString(params)}`),
  getUser: (id) => apiClient.get(ENDPOINTS.admin.userDetail(id)),
  assignRole: (data) => apiClient.post(ENDPOINTS.admin.assignRole, data),
  suspendUser: (id, data) => apiClient.patch(ENDPOINTS.admin.suspendUser(id), data),
  createTrafficAccount: (data) => apiClient.post(ENDPOINTS.admin.createTrafficAccount, data),
  listAds: () => apiClient.get(ENDPOINTS.admin.ads),
  createAd: (data) => apiClient.post(ENDPOINTS.admin.ads, data),
  updateAd: (id, data) => apiClient.patch(`${ENDPOINTS.admin.ads}/${id}`, data),
  distributeRosters: (data) => apiClient.post(ENDPOINTS.admin.distributeRosters, data),
  auditLogs: (params) => apiClient.get(`${ENDPOINTS.admin.audit}${buildQueryString(params)}`),
  reports: (params) => apiClient.get(`${ENDPOINTS.admin.reports}${buildQueryString(params)}`),
  verifyRoster: (token) => apiClient.get(ENDPOINTS.verify.roster(token)),
  pendingReviews: () => apiClient.get(ENDPOINTS.admin.reviewsPending),
  moderateReview: (id, adminStatus) =>
    apiClient.patch(ENDPOINTS.admin.moderateReview(id), { adminStatus }),
  getPrivacy: () => apiClient.get(ENDPOINTS.admin.privacy),
  updatePrivacy: (content) => apiClient.put(ENDPOINTS.admin.privacy, { content }),
  getRegistrationSettings: () => apiClient.get(ENDPOINTS.admin.registration),
  updateRegistrationSettings: (data) => apiClient.put(ENDPOINTS.admin.registration, data),
  confirmEnrollmentPayment: (id, amount, gatewayRef) =>
    apiClient.post(ENDPOINTS.admin.confirmEnrollmentPayment(id), { amount, gatewayRef }),
  getUserWallet: (id) => apiClient.get(ENDPOINTS.admin.userWallet(id)),
  creditUserWallet: (id, data) => apiClient.post(ENDPOINTS.admin.creditUserWallet(id), data),
  listFaq: () => apiClient.get(ENDPOINTS.admin.faq),
  createFaq: (data) => apiClient.post(ENDPOINTS.admin.faq, data),
  updateFaq: (id, data) => apiClient.patch(ENDPOINTS.admin.faqDetail(id), data),
  deleteFaq: (id) => apiClient.delete(ENDPOINTS.admin.faqDetail(id)),
  listRequirements: () => apiClient.get(ENDPOINTS.admin.requirements),
  createRequirement: (data) => apiClient.post(ENDPOINTS.admin.requirements, data),
  updateRequirement: (id, data) => apiClient.patch(ENDPOINTS.admin.requirementDetail(id), data),
  deleteRequirement: (id) => apiClient.delete(ENDPOINTS.admin.requirementDetail(id)),
  listTestimonials: () => apiClient.get(ENDPOINTS.admin.testimonials),
  createTestimonial: (data) => apiClient.post(ENDPOINTS.admin.testimonials, data),
  updateTestimonial: (id, data) => apiClient.patch(ENDPOINTS.admin.testimonialDetail(id), data),
  deleteTestimonial: (id) => apiClient.delete(ENDPOINTS.admin.testimonialDetail(id)),
}
